# Load WiC dataset

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('WIC_default_V4_emb.csv')

In [3]:
data

,Unnamed: 0.1,Unnamed: 0,keyword,POS,indices,sentence1,sentence2,human_label,freq,log2freq,default2,emb1,emb2
0,0,0,carry,V,2-1,You must carry your camping gear .,Sound carries well over water .,F,51781,15.660135,F,"[0.36855340003967285, 0.21410489082336426, 0.3...","[0.7610353827476501, 0.24949008226394653, 0.42..."
1,1,1,go,V,2-6,Messages must go through diplomatic channels .,Do you think the sofa will go through the door ?,F,1425686,20.443225,T,"[-0.0852346196770668, -0.13542714715003967, 0....","[-0.41432949900627136, -0.5187293291091919, -0..."
2,2,2,break,V,0-2,Break an alibi .,The wholesaler broke the container loads into ...,F,92773,16.501417,F,"[-0.09557104855775833, 0.6806768774986267, -0....","[0.6646726131439209, 0.3640071749687195, -0.33..."
3,3,3,cup,N,8-4,He wore a jock strap with a metal cup .,Bees filled the waxen cups with honey .,T,59218,15.853748,F,"[0.04534776136279106, 0.15553200244903564, -0....","[0.5837751626968384, 0.7275094985961914, 0.373..."
4,4,4,academy,N,1-2,The Academy of Music .,The French Academy .,F,8268,13.013323,T,"[0.6533669233322144, 0.41288065910339355, 0.14...","[0.38001948595046997, 0.5047792196273804, -0.5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5409,5409,5409,krona,N,4-8,Piecas kronas — five krona .,Kronas kurss — the exchange rate of the krona .,T,20,4.321928,T,"[-0.338161438703537, -0.29280316829681396, -0....","[0.2160266935825348, -0.6211860775947571, 0.11..."
5410,5410,5410,conflict,N,3-1,The harder the conflict the more glorious the ...,The conflict between the government and the re...,T,6941,12.760928,T,"[-0.4126608669757843, -0.009200280532240868, 0...","[-0.23549480736255646, -0.05389336124062538, -..."
5411,5411,5411,answer,V,0-0,Answer the riddle .,Answer a question .,T,92806,16.501930,T,"[0.058757320046424866, 0.6233664155006409, 0.3...","[0.05365370213985443, 0.27401450276374817, -0...."
5412,5412,5412,play,V,0-0,Play the casinos in Trouville .,Play the races .,T,242591,17.888167,T,"[0.12210450321435928, 0.0381808802485466, 0.67...","[0.06764652580022812, -0.25057026743888855, 0...."
5413,5413,5413,invasion,N,1-1,An invasion of bees .,An invasion of mobile phones .,T,6222,12.603163,T,"[-0.10689730942249298, 1.0605946779251099, -0....","[-0.02201126515865326, 0.32505595684051514, -0..."

In [5]:
# shaffle all dataFrame
data = data.sample(frac=1).reset_index(drop=True)
data

,Unnamed: 0.1,Unnamed: 0,keyword,POS,indices,sentence1,sentence2,human_label,freq,log2freq,default2,emb1,emb2
0,4145,4145,cast,N,5-2,Her features had a delicate cast to them .,The delicate cast of his features .,T,14255,13.799180,T,"[0.24237412214279175, -0.803604006767273, -0.1...","[0.1462339460849762, -0.27849602699279785, -0...."
1,4300,4300,use,V,2-6,We can use this mathematical formula to solve ...,He does n't know how to use a computer .,T,177732,17.439344,T,"[-0.2957974672317505, -0.01667402870953083, 0....","[-0.13562947511672974, 0.7027122974395752, -0...."
2,1169,1169,send,V,1-7,"To send a message , or a letter .","Every day at two o'clock , he sends his secret...",T,76007,16.213845,F,"[0.01184543315321207, 0.07255490124225616, 0.4...","[0.2891814112663269, 0.4338524043560028, 0.395..."
3,1031,1031,variety,N,3-0,The range and variety of his work is amazing .,Varieties are frequently recognized in botany .,F,10280,13.327553,F,"[-0.11183591187000275, -0.22079649567604065, 1...","[-0.32044661045074463, -0.7519974708557129, 0...."
4,3467,3467,be,V,4-1,When will the meeting be ?,There were two hundred people at his funeral .,T,3633611,21.792973,F,"[0.5013243556022644, -1.6293790340423584, 0.67...","[0.18315018713474274, -0.5413918495178223, 0.5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5409,3348,3348,admit,V,1-2,To admit a serious thought into the mind .,They were admitted into his house .,T,56539,15.786959,F,"[0.05158669129014015, 0.12826386094093323, 0.2...","[-0.054812949150800705, -0.28052547574043274, ..."
5410,4208,4208,court,N,7-1,The king will visit the duke 's court .,Pay court to the emperor .,F,44196,15.431628,T,"[0.6473537683486938, 0.30600738525390625, 0.56...","[0.40774673223495483, -0.11532182991504669, 0...."
5411,1976,1976,time,N,7-1,He was a great actor in his time .,The time of year for planting .,T,1628590,20.635192,F,"[-0.7827091217041016, 0.15824365615844727, -0....","[-1.012439489364624, 0.4693511724472046, 0.403..."
5412,1480,1480,head,N,1-7,The head of the list .,I 've got to go to the head .,F,1197304,20.191358,T,"[-0.7420426607131958, -0.22670310735702515, 0....","[0.4049907624721527, 0.4502016305923462, 0.511..."
5413,2538,2538,dwelling,N,6-3,The old house served as a dwelling for Albert .,I was doing dwelling in the cave .,T,1279,10.320801,F,"[0.36963045597076416, 0.34646087884902954, 0.2...","[0.2949926555156708, 0.4461063742637634, -0.03..."

In [6]:
data.index

RangeIndex(start=0, stop=5414, step=1)

In [7]:
# 10 bins split
maxy = max(data['freq'])
maxy

7477811

# Prepare 5 cross-validations dataset

In [9]:
import numpy as np

In [44]:
no_bin=10
move = np.log2(maxy)/no_bin
validation_index={i:[] for i in range(1,6)}
# {validation index 1 to 5 with the index of 5 validation}
total=0
for index in range(no_bin):
    left = index*move
    if index == no_bin-1:
        right = np.log2(maxy)+5
    else:
        right = (index+1)*move
    temp_index = list(data[(data['log2freq']>=left) & (data['log2freq']<right)].index)
    total+=len(temp_index)
    #print(left, right, len(temp_index))
    for validation in range(5):
        val_left=(validation)*round(len(temp_index)/5)
        val_right=(validation+1)*round(len(temp_index)/5)
        if validation!=4:
            for member in temp_index[val_left:val_right]:
                validation_index[validation+1].append(member)
        else:
            for member in temp_index[val_left:]:
                validation_index[validation+1].append(member)
        #print(validation_index)

In [51]:
data.loc[validation_index[5]]

,Unnamed: 0.1,Unnamed: 0,keyword,POS,indices,sentence1,sentence2,human_label,freq,log2freq,default2,emb1,emb2
4996,4167,4167,channelize,V,0-0,Channelize a stream .,Channelize the country for better transportati...,F,2,1.000000,T,"[0.3666633367538452, 0.022788114845752716, 0.3...","[0.32252535223960876, -0.3472224473953247, 0.1..."
5318,2713,2713,roughcast,V,0-1,Roughcast a wall .,To roughcast a wall or building .,T,3,1.584963,T,"[0.28704795241355896, -0.3306847810745239, -0....","[0.8091495037078857, -0.09677378833293915, -0...."
4495,5409,5409,krona,N,4-8,Piecas kronas — five krona .,Kronas kurss — the exchange rate of the krona .,T,20,4.321928,T,"[-0.338161438703537, -0.29280316829681396, -0....","[0.2160266935825348, -0.6211860775947571, 0.11..."
4554,4299,4299,reticulation,N,1-1,The reticulation of a leaf .,The reticulation of a photographic emulsion .,T,5,2.321928,T,"[-0.20209498703479767, -0.43575870990753174, 0...","[-0.43539056181907654, -0.5499632954597473, 0...."
4860,3819,3819,krona,N,8-1,Kronas kurss — the exchange rate of the krona .,"Papīra krona — paper krona ( i.e. , bills , ba...",T,20,4.321928,T,"[0.2160266935825348, -0.6211860775947571, 0.11...","[0.05378809571266174, -0.5829477310180664, -0...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5332,1151,1151,be,V,4-1,When will the meeting be ?,It is almost eight .,T,3633611,21.792973,F,"[0.5013243556022644, -1.6293790340423584, 0.67...","[-0.6188017725944519, -0.2317473590373993, 0.5..."
5336,1756,1756,have,V,0-0,Have an assistant .,Have a lover .,T,7356386,22.810566,T,"[0.3402656018733978, 0.355078786611557, 0.3830...","[0.47860318422317505, -0.3042026460170746, 0.5..."
5341,748,748,take,V,0-0,Take shelter from the storm .,Take a test .,F,2184370,21.058786,T,"[0.1774645447731018, 0.2396056056022644, -0.32...","[0.16884391009807587, -0.41957584023475647, 0...."
5354,4191,4191,take,V,0-0,Take vengeance .,Take steps .,T,2184370,21.058786,T,"[0.47523194551467896, 0.14770889282226562, -0....","[0.22254709899425507, -0.017286593094468117, -..."
5411,1976,1976,time,N,7-1,He was a great actor in his time .,The time of year for planting .,T,1628590,20.635192,F,"[-0.7827091217041016, 0.15824365615844727, -0....","[-1.012439489364624, 0.4693511724472046, 0.403..."

In [55]:
# divide into csv 1 to 5
all_validation = [1,2,3,4,5]
for i in range(1,6): # i = 1 to 5
    test = data.loc[validation_index[i]]
    train_index=[]
    for h in all_validation:
        if h!=i:
            for member in validation_index[h]:
                train_index.append(member)
    train=data.loc[train_index]
    test.to_csv('WIC_test_val'+str(i)+'.csv')
    train.to_csv('WIC_train_val'+str(i)+'.csv')